### ISSUE TITLE
Running target for motor.MoveTo()

### ISSUE THREAD

**Issue by antonvh** [charlesweir/BrickPython#2]
After the co-routine is started is started with a certain value for the motor to move to, the target can't be changed anymore because it has become a local value in the co-routine. What would be the best way to implement a moving target in your framework? A global variable? Killing the co-routine when the target changes (this makes you loose running integrals and derivatives in the PID routine)? Passing a mutable type to the co-routine, e.a. [target] instead of just int(target)? Another option? 

If you point me in the right direction, I'll fork and expand the library.

**Comment by charlesweir** [comment]
Hi,

I’d not thought of this issue, but it’s interesting.  But I’d query your statement…

Ø  Killing the co-routine when the target changes (this makes you loose running integrals and derivatives in the PID routine)?

Does that matter?  The integrals and derivatives will be wrong anyway if you change the target.  So I’d suggest doing it that way.

Best regards,

Charles

**Comment by antonvh** [comment]
Thanks. I figured out another option: breaking the for loop. Maybe more
elegant. Will try on the BrickPi tonight...

def followTheMovingTargetv1(self):
        '''Coroutine that follows a moving target which is a property of
the app class
        '''
        motorA = self.motor('A')
        motorA.zeroPosition()
        while True:
            self.last_target = self.moving_target

```
        for i in motorA.moveTo(self.moving_target):
            if self.last_target != self.moving_target: break
            yield
```

def followTheMovingTargetv2(self):
        '''Coroutine that follows a moving target which is a property of
the app class
        '''
        motorA = self.motor('A')
        motorA.zeroPosition()
        self.last_target = self.moving_target #the moving target is changed
outside this coroutine.
        # I wonder if last_target without .self would do the job just as
wel...
        self.co = motorA.moveTo(self.moving_target)
        self.addActionCoroutine( self.co )
        while True:
            if self.last_target != self.moving_target:
                self.last_target = self.moving_target
                self.stopCoroutine(self.co)
                self.co = motorA.moveTo(self.moving_target)
                self.addActionCoroutine(self.co)
            yield

**Comment by antonvh** [comment]
The first option worked, after some debugging. BUT BrickPython has a some overhead and performance is shaky at best. I reverted back to vanilla BrickPi with threading for better performance.
